const MainSystem = require("./MainSystem");
const { CashPayment, CreditPayment } = require("./Payment");
let mainSystem = new MainSystem("Dublin");
mainSystem.displaySections();
mainSystem.selectSection("Hourly", true, "12345");
mainSystem.sections.get("Hourly").scanTicket(1);
mainSystem.startExitProcess(1, "Hourly");
let payment = new CashPayment(10);
mainSystem.takePayment(payment, "Hourly", 1);
// console.log(mainSystem);
